/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WaitlistEntry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  'addToWaitlist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getWaitlist' : IDL.Func([], [IDL.Vec(WaitlistEntry)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WaitlistEntry = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    'addToWaitlist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getWaitlist' : IDL.Func([], [IDL.Vec(WaitlistEntry)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };